version: '3.8'

services:
  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/education
    depends_on:
      - mongodb


  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: ["mongod --replSet rs0"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s


volumes:
  mongodb_data: 